spring:
  # 静态资源处理
  resources:
    # 启用静态资源处理器，默认启用
    add-mappings: true
    # 启用静态资源处理器，默认启用
    cache:
      cachecontrol:
        # 缓存响应时间，单位秒
        max-age: 3600
    chain:
      # 资源链启用缓存，默认启用
      cache: true
      # 启用资源链，默认禁用
      enabled: true
      # 启用资源压缩（gzip，brotli），默认禁用
      compressed: true
      # 启用h5应用缓存，默认禁用
      html-application-cache: true
    static-locations: classpath:/static/

  # thymeleaf配置
  thymeleaf:
    # 禁用缓存
    cache: false
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&chartcterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      # 连接名
      pool-name: DateHikarCP
      # 最下空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间，默认10分钟（600000）
      idle-timeout: 1800000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认30分钟（1800000）
      max-lifetime: 1800000
      # 连接超时时间，默认30秒（30000）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  redis:
    # 服务器地址
    host: 192.168.198.3
    # 端口
    port: 6379
    # 数据库
    database: 0
    # 连接超时时间
    connect-timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数，默认8
        max-active: 8
        # 最大连接阻塞等待， 默认-1
        max-wait: 10000ms
        # 最大空闲连接数，默认8
        max-idle: 200
        # 最小连接数，默认0
        min-idle: 5
  # RabbitMQ配置
  rabbitmq:
    # 服务器地址
    host: 192.168.198.3
    # 用户名
    username: guest
    # 密码
    password: guest
    # 虚拟主机
    virtual-host: /
    # 端口
    port: 5672
    listener:
      simple:
        # 消费者最小数量
        concurrency: 10
        # 消费者最大数量
        max-concurrency: 10
        # 限制消费者每次只能处理一条消息，处理完毕后再处理吓一条消息
        prefetch: 1
        # 启动时是否默认启动容器，默认为true
        auto-startup: true
        # 消息被拒绝时是否重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        # 发布重试，默认false
        enabled: true
        # 重试时间，默认1000ms
        initial-interval: 1000ms
        # 最大重试次数，默认是3
        max-attempts: 3
        # 最大重试时间间隔，默认1000ms
        max-interval: 1000ms
        # 重试间隔乘数，比如2.0，第一次为10s，第二次为20s，第三次为40s
        multiplier: 1

# mybatis-plus配置
mybatis-plus:
  # 配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置Mybatis数据返回类型别名（默认别名是pojo类名）
  type-aliases-package: com.sumu.seckill.pojo

# MyBatis SQL打印（方法所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.sumu.seckill.mapper: debug