spring:
  # thymeleaf配置
  thymeleaf:
    # 禁用缓存
    cache: false
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&chartcterEncoding=UTF-8&serverTime=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      # 连接名
      pool-name: DateHikarCP
      # 最下空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间，默认10分钟（600000）
      idle-timeout: 1800000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认30分钟（1800000）
      max-lifetime: 1800000
      # 连接超时时间，默认30秒（30000）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

# mybatis-plus配置
mybatis-plus:
  # 配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置Mybatis数据返回类型别名（默认别名是pojo类名）
  type-aliases-package: com.sumu.seckill.pojo

# MyBatis SQL打印（方法所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.sumu.seckill.mapper: debug